<?php return array (
  0 => 'No tasks here',
  1 => 'Calendar',
  2 => 'Enables viewing project data in a calendar. Global calendar is available plus a calendar for each project and user',
  3 => 'Module will be deactivated. Data that is shown in the calendars will not be deleted',
  4 => ':user\'s calendar',
  5 => 'Schedule',
  6 => 'Sunday',
  7 => 'Monday',
  8 => 'Tuesday ',
  9 => 'Wednesday',
  10 => 'Thursday',
  11 => 'Friday',
  12 => 'Saturday',
  13 => 'Tickets',
); ?>