<?php return array (
  0 => 'Notify People',
  1 => 'Category',
  2 => 'Add discussion',
  3 => 'New Discussion',
  4 => 'Update Discussion',
  5 => 'Discussions',
  6 => 'There are no discussions on this page',
  7 => 'Discussion',
  8 => 'Replies',
  9 => 'Last Reply',
  10 => 'by <a href=":user_url">:user_name</a>',
  11 => 'No discussions in this category',
  12 => 'No discussions here',
  13 => 'All Discussions',
  14 => 'Manage Categories',
  15 => 'Discussion <a href=":url">:name</a> has been created',
  16 => 'Set Milestone and Category',
  17 => 'Set Category',
  18 => 'Set Visibility',
  19 => 'Page :page',
  20 => 'About Discussions',
  21 => 'Just Like Online Forums',
  22 => 'Discussions let you create a number of topics and discuss them with your team and clients. It works just like online forums - system will tell you when there are new messages in a topic and discussions with most recent comments are listed on top',
  23 => 'Organize in Categories and Associate with Milestones',
  24 => 'Discussions can be sorted in categories and associated with milestones; both relations are optional. Filter discussions by category using the tabs on the right',
  25 => 'Attach Unlimited Number of Files',
  26 => 'Every discussion message can have an unlimited number of attachments. System will use icons for various file types and thumbnails for images',
  27 => 'Subscribe to a discussion to receive an email notification when new message is posted. Discussion subscribers can be managed using Manage Subscriptions tool (available from Options menu)',
  28 => 'Failed to pin selected discussion',
  29 => 'Failed to unpin selected discussion',
  30 => 'Discussion :discussion_name has been started',
  31 => 'Discussion ":name" has been updated',
  32 => 'Discussion has been successfully pinned',
  33 => 'Discussion has been successfully unpinned',
  34 => '<strong>Pinned</strong> - This discussion is pinned',
  35 => 'Adds discussion boards to projects',
  36 => 'Module will be deactivated. All discussions from all projects will be deleted',
  37 => 'Discussion categories',
  38 => 'Toggle Details',
  39 => 'Exporting discussions data...',
  40 => 'Pin',
  41 => '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion',
  42 => '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> project',
  43 => ':user_name pinned <a href=":object_url">:object_name</a> discussion',
  44 => '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion',
  45 => '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> project',
  46 => ':user_name unpinned <a href=":object_url">:object_name</a> discussion',
  47 => 'Summary is required (min 3 letters)',
  48 => 'Message is required (min 3 letters)',
); ?>