<?php return array (
  0 => 'Backup Settings',
  1 => 'How many backups to keep:',
  2 => 'Enable backup:',
  3 => 'Automatic backup is <strong>enabled</strong>',
  4 => 'Your next backup will be approximately <strong>:size</strong> in size',
  5 => 'Automatic backup is <strong>disabled</strong>',
  6 => ':number_of_backups last backups will be kept',
  7 => 'All backups will be kept',
  8 => 'Existing backups',
  9 => 'Backup Date',
  10 => 'Backup Size',
  11 => 'Backup State',
  12 => 'Valid',
  13 => 'Backup folder size: <strong>:size</strong>',
  14 => 'Backup',
  15 => 'Automatically create daily backup of your activeCollab data',
  16 => 'Module will be deactivated. Backups created with this module will not be deleted.',
  17 => 'Backup settings have been updated',
  18 => 'Automatic backup of your activeCollab installation',
  19 => 'Backup is Corrupted',
  20 => 'Backup is Corrupted. Database backup is missing',
  21 => '<strong>:filesize</strong> is file size of database backup',
  22 => '<strong>:count</strong> uploaded files backed up',
  23 => '<strong>:count</strong> avatars backed up',
  24 => '<strong>:count</strong> projects icons backed up',
  25 => '<strong>:count</strong> customer logos backed up',
); ?>