<?php return array (
  0 => 'About Files',
  1 => 'Upload Files, File Revisions and Collaborate',
  2 => 'Use Files section to upload files, discuss them, upload and compare versions and more. You can upload and track versions of any file. Files attached to objects in other sections of project are also listed here',
  3 => 'Organize in Categories and Associate with Milestones',
  4 => 'Files can be sorted in categories and associated with milestones; both relations are optional. Filter files by category using the tabs on the right',
  5 => 'Have a Discussion with your Team or Clients',
  6 => 'Post an unlimited number of comments. Use them to discuss file and file revisions with your colleagues and clients',
  7 => 'Subscribe to a file to receive email notification when new revision is uploaded or new comment is posted. The Person who uploaded the file can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)',
  8 => 'Older Versions',
  9 => 'Delete Permanently',
  10 => 'Page :page',
  11 => 'Thumbnail',
  12 => 'File Details',
  13 => 'File',
  14 => 'Attached To',
  15 => 'Download',
  16 => 'There are no files in this category',
  17 => 'Upload now',
  18 => 'There are no files to show',
  19 => 'All Files',
  20 => 'All Attachments',
  21 => 'Manage Categories',
  22 => 'Edit File Details',
  23 => 'Category',
  24 => 'Files',
  25 => 'There are no files on this page',
  26 => 'Latest Version',
  27 => 'This has no revisions',
  28 => 'First Version',
  29 => 'New Version',
  30 => 'Move To Trash',
  31 => 'Move To Category',
  32 => '&lt;None&gt;',
  33 => 'Select File',
  34 => 'You are about to upload new version of <a href=":url">":name"</a> file. Older versions of this file will not be deleted but saved for future reference',
  35 => 'Notify People',
  36 => 'File <a href=":url">:name</a> has been created',
  37 => 'Set Milestone and Category',
  38 => 'Set Category',
  39 => 'Set Visibility',
  40 => 'Upload Files',
  41 => 'Description <i>(optional)</i>',
  42 => 'Add Another File',
  43 => '<strong>Note</strong>: Max upload size is :max_size per file',
  44 => 'Upload',
  45 => 'File Name',
  46 => 'Image preview. <a href=":url">Click to download</a> full size image',
  47 => 'Description for this file is not provided',
  48 => 'Invalid file - last revision was not found',
  49 => 'Please select what you want to do with selected tickets',
  50 => 'Please select files that you would like to update',
  51 => 'File ":name" has been updated',
  52 => 'File not uploaded',
  53 => ':count attachments deleted',
  54 => ':count files moved to trash',
  55 => ':count files updated',
  56 => 'You haven\'t selected any file for upload',
  57 => 'Adds file repository to each project. Highlights: files support versioning, can have comments, email notifications, can be organized in categories and more...',
  58 => 'Module will be deactivated. All files created with this module will be deleted. Files attached to objects in other modules (tickets, comments etc) will not be deleted',
  59 => 'File categories',
  60 => 'Exporting files data...',
  61 => '<a href=":user_url">:user_name</a> uploaded a new file',
  62 => '<a href=":user_url">:user_name</a> uploaded a new file to <a href=":project_view_url">:project_name</a> project',
  63 => '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file',
  64 => '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file in <a href=":project_view_url">:project_name</a> project',
  65 => 'File name is required',
); ?>