<?php return array (
  0 => 'About Milestones',
  1 => 'Milestones Mark Key Points in a Project',
  2 => 'Milestones mark key points in a project so you can have a bird-eye view over things that needs to be done, when and who is responsible. Milestone can be a single day event or a time period with start and due date. When you need more details, you can click on a milestone\'s name to "zoom in" and see all related discussions, files and tasks',
  3 => 'Keep Your Calendar Application in Sync with Milestones',
  4 => 'If you want to have milestones synchronized with calendars in your favorite calendar application (iCal, Outlook 2007, Google Calendar), then subscribe to iCalendar feed provided by the system. On the Calendar page you can find global feed with milestones and tasks from all active projects. The system also provides a feed for each project and you can find it by visiting overview page of the particular project',
  5 => 'Email Notifications',
  6 => 'Subscribe to a milestone to receive email notification when it is completed or reopened. The person responsible for the milestone can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)',
  7 => 'Start on',
  8 => 'Notes',
  9 => 'New Milestone',
  10 => 'Completed Milestones',
  11 => 'There are no completed milestones in this project. <a href=":add_url">Create a milestone</a>.',
  12 => 'Edit Milestone',
  13 => 'Milestones',
  14 => 'Milestone',
  15 => 'Active milestones',
  16 => 'iCalendar',
  17 => 'No active milestones here',
  18 => 'Would you like to <a href=":add_url">create one</a>',
  19 => 'Milestone <a href=":url">:name</a> has been created',
  20 => 'Back',
  21 => 'Reschedule milestone',
  22 => 'With Successive Milestones',
  23 => 'Also reschedule all tickets and tasks that belong to milestones you are rescheduling',
  24 => 'Reschedule',
  25 => 'From / To',
  26 => 'Add to Milestone',
  27 => 'No notes...',
  28 => 'No tasks in this milestone...',
  29 => 'Milestone ":name" has been created',
  30 => 'Milestone ":name" has been updated',
  31 => 'or',
  32 => '<a href=":url">Click here</a> if you wish to reschedule this milestone',
  33 => 'You don\'t have permission for this action',
  34 => 'Exporting milestones data...',
  35 => 'Unknown Milestone',
  36 => 'This milestone does not have any successive milestones',
  37 => 'Adjust all successive milestone by the same number of days',
  38 => 'Adjust only selected successive milestones by the same number of days',
  39 => 'Don\'t change anything',
  40 => 'Add milestones to projects',
  41 => 'Start date is not valid',
  42 => 'Due date is not valid',
  43 => 'Milestone name is required',
  44 => 'Start date is required',
  45 => 'Due date is required',
  46 => 'Start date needs to be before due date',
); ?>