<?php return array (
  0 => 'Submit Ticket / :company',
  1 => 'Submit Ticket',
  2 => 'Your Email Address',
  3 => 'Your Name',
  4 => 'Category',
  5 => 'Full Description',
  6 => 'Type the code shown',
  7 => 'Public Submit Settings',
  8 => 'Project for tickets:',
  9 => 'Enable captcha:',
  10 => 'Enable public submit:',
  11 => 'When enabled, Public Submit module will let people submit tickets through a form on your website without having to be a registered and logged in the system. This module is great for receiving support requests or getting feedback from users',
  12 => 'Public Submit is <strong>enabled</strong>',
  13 => 'Submission form is located here: <a href=":url" target="_blank">:url</a>',
  14 => 'After user submits data, a new ticket is created in <a href=":url">:project_name</a> project.',
  15 => 'You need to specify default project for newly created tickets first.',
  16 => 'GD Library with FreeType2 is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>',
  17 => 'Public Submit is <strong>disabled</strong>',
  18 => 'GD Library is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>',
  19 => 'Public Submit',
  20 => 'Public Submit settings have been updated',
  21 => 'Code you entered is not valid',
  22 => 'Information about Public Submit module',
  23 => 'Submit tickets without having an activeCollab account',
  24 => 'Module will be deactivated. Data you create using this module will not be deleted',
); ?>