<?php return array (
  0 => 'Full description',
  1 => 'New Checklist',
  2 => 'Completed Checklists',
  3 => ':open open tasks of :total tasks in the list',
  4 => 'There are no active checklists here',
  5 => 'Edit checklist',
  6 => 'Checklists',
  7 => 'Active Checklist',
  8 => 'There are no active checklists in this project',
  9 => 'Completed Checklist',
  10 => 'Checklist',
  11 => 'Active Checklists',
  12 => ':open_count open tasks of :total_count tasks in list',
  13 => 'Assignees for Tasks',
  14 => 'Checklists <a href=":url">:name</a> has been created',
  15 => 'Set Milestone',
  16 => 'Set Visibility',
  17 => 'Open',
  18 => 'Description for this checklist is not provided',
  19 => 'About Checklists',
  20 => 'Lists of Tasks',
  21 => 'Checklist is a list of tasks that need to be done in order to get a checklist completed. When all tasks in the checklist are completed, the checklist is completed automatically. Every task in a list can have priority, due date and multiple assignees',
  22 => 'Subscribe to checklist tasks to receive email notification when tasks are completed or reopened',
  23 => 'Adds simple task lists to projects',
  24 => 'Module will be deactivated and all checklists from all projects will be deleted',
  25 => 'Checklist :name has been added',
  26 => 'Checklist :name has been updated',
  27 => 'Exporting checklists data...',
  28 => 'Checklist summary is required',
); ?>