<?php return array (
  0 => 'Category Name',
  1 => 'Edit Category',
  2 => 'Document Categories',
  3 => 'There are no document categories',
  4 => 'Document',
  5 => 'Category',
  6 => 'Notify People',
  7 => 'Normal &mdash; <span class="details">Visible to everyone who has access to Documents section</span>',
  8 => 'Private &mdash; <span class="details">Visible only to members of :owner_company company</span>',
  9 => 'Normal &mdash; <span class="details">Visible to anyone who has access to Documents section</span>',
  10 => 'Add Document',
  11 => 'Add Text',
  12 => 'Edit Document',
  13 => 'Documents',
  14 => 'Not pinned. Click to pin to top',
  15 => 'Not pinned',
  16 => 'Pinned. Click to unpin',
  17 => 'Pinned',
  18 => 'This document is visible only to members of :company_name company',
  19 => 'No documents here. Would you like to <a href=":add_text_url">create a text document</a> or <a href=":upload_file_url">upload a file</a>?',
  20 => 'Sorry, no documents here',
  21 => 'All Documents',
  22 => 'Manage Categories',
  23 => 'Upload New File',
  24 => 'File',
  25 => '<strong>Note</strong>: Largest file you can upload must be smaller than :max_size',
  26 => 'Upload file',
  27 => 'Upload',
  28 => 'Are you sure that you want to permanently delete this document?',
  29 => 'Documents Module',
  30 => 'Can access docs?',
  31 => 'Can add docs?',
  32 => 'About Documents',
  33 => 'Post Text and Upload Files',
  34 => 'Documents are globally available sections where you can post articles and files. When a user has sufficient permissions to access the Documents section, a Docs icon will be displayed in the toolbar',
  35 => 'Who Can See What?',
  36 => 'Documents use similar visibility model as object in projects. There are two visibility levels:',
  37 => '<strong>Public documents</strong> are visible to everyone who can access Documents section',
  38 => '<strong>Private documents</strong> are visible only to people who have role with can_see_private_objects permission set to Yes',
  39 => 'Category ":name" has been created',
  40 => 'Category ":category_name" has been updated',
  41 => 'Document category ":name" has been deleted',
  42 => 'Failed to delete ":name" document category',
  43 => 'New Text Document',
  44 => 'Upload File',
  45 => 'Failed to pin document ":document_name"',
  46 => 'Failed to unpin document ":document_name"',
  47 => 'Failed to delete ":document_name"',
  48 => 'Document ":document_name" has been created',
  49 => 'Document ":document_name" has been uploaded',
  50 => 'Document ":document_name" has been updated',
  51 => 'Document ":document_name" has been pinned',
  52 => 'Document ":document_name" has been unpinned',
  53 => 'Document ":document_name" has been deleted',
  54 => '<strong>Private</strong> - only members with: :roles roles can see this document.',
  55 => 'Adds global document management system',
  56 => 'Module will be deactivated. All data generated using it will be deleted',
  57 => 'Docs',
  58 => 'Please insert new document category name',
  59 => 'Category name needs to be unique',
  60 => 'Category name must be at least 3 characters long',
  61 => 'Document name must be at least 3 characters',
  62 => 'Category is required',
); ?>