<?php return array (
  0 => 'Jump to Project',
  1 => 'Quick Search',
  2 => 'Working',
  3 => 'Hidden Email History',
  4 => 'Open Full Size (:widthx:heightpx)',
  5 => 'Full Size Image',
  6 => 'Required',
  7 => 'Min :min characters long',
  8 => 'Max :max characters long',
  9 => 'Values do not match',
  10 => 'Invalid address format',
  11 => 'Invalid URL format',
  12 => 'Value need to be a number',
  13 => 'Value need to be a whole number',
  14 => 'Value should contain only letters',
  15 => 'Value should contain only numbers and letters',
  16 => 'All changes you have made to this page will be lost!',
  17 => 'Choose Uploaded Image',
  18 => 'Insert Link',
  19 => 'Clean text and paste',
  20 => 'Title',
  21 => 'Subtitle',
  22 => 'Quote',
  23 => 'Important',
  24 => 'Note',
  25 => 'Updated',
); ?>